#ifndef CASVP_CONFIG_H
#define CASVP_CONFIG_H

#define CASVP_FORMOSA_CSR_LOCAL_SIZE_Z 64
#define CASVP_FORMOSA_CSR_NUM_GROUPS_X 72
#define CASVP_FORMOSA_CSR_NUM_GROUPS_Y 80
#define CASVP_FORMOSA_CSR_NUM_GROUPS_Z 88
#define CASVP_FORMOSA_CSR_GLOBAL_OFFSET_X 96
#define CASVP_FORMOSA_CSR_GLOBAL_OFFSET_Y 104
#define CASVP_FORMOSA_CSR_GLOBAL_OFFSET_Z 112
#define CASVP_FORMOSA_CSR_ACK 120
#define CASVP_FORMOSA_CSR_COMPLETION_KERNEL_ID 128
#define CASVP_FORMOSA_CSR_STATUS 136
#define CASVP_FORMOSA_CSR_ECID 144
#define CASVP_FORMOSA_CSR_MEPC 168
#define CASVP_FORMOSA_CSR_MTVAL 176
#define CASVP_FORMOSA_CSR_MCAUSE 160
#define CASVP_FORMOSA_CSR_EWID 152
#define CASVP_FORMOSA_THREADS_PER_WARP 32
#define CASVP_FORMOSA_WARPS_PER_CORE 32
#define CASVP_FORMOSA_NUM_CORES 1
#define CASVP_FORMOSA_STACK_SIZE_PER_THREAD 1024
#define CASVP_FORMOSA_LOCAL_MEM_SIZE 134217728
#define CASVP_FORMOSA_CACHE_SIZE 4096
#define CASVP_FORMOSA_CACHE_BLOCK_SIZE 64
#define CASVP_FORMOSA_GLOBAL_MEM_SIZE 4294967296
#define CASVP_FORMOSA_CSR_START 0
#define CASVP_FORMOSA_CSR_ENTRY_PC 8
#define CASVP_FORMOSA_CSR_KERNEL_PC 16
#define CASVP_FORMOSA_CSR_KERNEL_ARG 24
#define CASVP_FORMOSA_CSR_LAUNCH_KERNEL_ID 32
#define CASVP_FORMOSA_CSR_DIM 40
#define CASVP_FORMOSA_CSR_LOCAL_SIZE_X 48
#define CASVP_FORMOSA_CSR_LOCAL_SIZE_Y 56

#endif
